In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])  #List
print(arr)

arr1 = np.array((1,2,3,4,5))   #tuple
print(arr1)

print(type(arr))
print(arr[1])
print(arr[1]+arr[3])
print(arr[1]*arr[2])
print(arr[1]/arr[2])
print(arr[1]//arr[2])  #floor division
print(arr[1] & arr[2])  #Bitwise and

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
2
6
6
0.6666666666666666
0
2


#2D and 3D


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row",arr[0,1])
print("5th element on the 2nd row", arr[1,4])
print("last element from the 2nd dim", arr[1,-1] )

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])


2nd element on 1st row 2
5th element on the 2nd row 10
last element from the 2nd dim 10
12


#Slicing

In [1]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:1,0:2])
print(arr[0:2,1:4])

[7 8 9]
[[1 2]]
[[2 3 4]
 [7 8 9]]
